
services:
  zoo-server:
    image: zookeeper
    container_name: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181
  admin-server:
    image: apache/dubbo-admin
    container_name: dubbo-admin
    depends_on:
    - zoo-server
    ports:
      - 8081:8080
    environment:
      - admin.registry.address=zookeeper://zoo-server:2181
      - admin.config-center=zookeeper://zoo-server:2181
      - admin.metadata-report.address=zookeeper://zoo-server:2181
version: "3"